import React from "react"

export default (
    <p>
Gentile Signore/a,<br/>
desideriamo informarLa, ai sensi dell’articolo 13 Regolamento UE 2016/679 sulla “Protezione dei Dati”, che le informazioni ed i dati acquisiti dalla nostra azienda nell’ambito di procedure di selezione del personale o da Lei forniti attraverso l’invio spontaneo del curriculum vitae o altrimenti acquisiti saranno oggetto di trattamento nel rispetto delle disposizioni sopra menzionate e degli obblighi di riservatezza che ispirano l’attività della Birra Peroni s.r.l.<br/>
Per trattamento di dati personali intendiamo qualsiasi operazione o insieme di operazioni, compiute con o senza l’ausilio di processi automatizzati e applicate a dati personali o insiemi di dati personali, come la raccolta, la registrazione, l’organizzazione, la strutturazione, la conservazione, l’adattamento o la modifica, l’estrazione, la consultazione, l’uso, la comunicazione mediante trasmissione, diffusione o qualsiasi altra forma di messa a disposizione, il raffronto o l’interconnessione, la limitazione, la cancellazione o la distruzione.<br/>
Il trattamento sarà effettuato con le seguenti modalità: i dati saranno trattati in forma cartacea e/o su supporto magnetico, elettronico o telematico (tramite la compilazione di form presenti sul nostro sito web). Laddove il Suo curriculum sia stato ricevuto in formato elettronico o su supporti diversi da quelli cartacei, La informiamo che i relativi files confluiranno in una apposita Banca Dati interna alla nostra azienda.<br/>
I Suoi dati personali potranno essere comunicati a società del Gruppo Birra Peroni s.r.l. di cui è parte la nostra azienda, ad altre società che potrebbero risultare interessate al suo profilo professionale, a soggetti da Lei stesso indicati nel CV ai fini delle verifiche e valutazioni del caso. <br/>
La informiamo che il conferimento dei dati è facoltativo e il loro eventuale mancato conferimento potrebbe comportare l’impossibilità da parte della nostra azienda di eseguire le procedure di valutazione del Suo profilo professionale e di gestire eventuali fasi successive.<br/>
La informiamo che i Suoi dati personali saranno conservati (in archivi elettronici o cartacei) fino ad un massimo di 24 mesi, e successivamente verranno cancellati, salvo Sua diversa segnalazione.<br/>
La informiamo altresì che i Suoi dati saranno raccolti, trattati e custoditi nel pieno rispetto di quanto previsto dall’art. 32 del Regolamento UE 2016/679, in materia di misure di sicurezza.<br/>
Gli estremi identificativi del Titolare del trattamento sono i seguenti: Birra Peroni s.r.l. – Via Renato Birolli, 8 – CAP 00155. La informiamo altresì che l’elenco aggiornato dei Responsabili del trattamento è da Lei richiedibile presso il dipartimento Risorse Umane di Birra Peroni S.r.l.. o sul sito web www.birraperoni.it. Per eventuali contatti ai fini dell’esercizio dei suoi diritti, potrà utilizzare i medesimi recapiti del titolare del trattamento come sopra riportati.<br/>
I dati saranno conservati presso la sede del Titolare, per i tempi definiti dalla normativa di riferimento. La informiamo altresì che tali dati saranno raccolti, trattati e custoditi nel pieno rispetto di quanto previsto dalle norme di legge.<br/>
E’ in ogni caso possibile per l’interessato avvalersi dei diritti di cui agli articoli del Regolamento UE 2016/679 da 15 a 23 cui espressamente si rinvia, revocando altresì il consenso in qualsiasi momento senza pregiudizio di liceità del trattamento basato sul consenso prestato prima della revoca, nonché proporre reclamo all’Autorità Garante dei dati personali con sede in Piazza di Monte Citorio n.121, 00186 Roma.<br/>
    </p>
)