import React from "react"

export default (
    <p>
        Gentile Signore/a,<br/>
desideriamo informarLa, ai sensi dell’articolo 13 Regolamento UE 2016/679 sulla “Protezione dei Dati”, che le informazioni ed i dati acquisiti dalla nostra azienda nell’ambito di procedure di selezione del personale o da Lei forniti attraverso l’invio spontaneo del curriculum vitae o altrimenti acquisiti saranno oggetto di trattamento nel rispetto delle disposizioni sopra menzionate e degli obblighi di riservatezza che ispirano l’attività della Birra Peroni s.r.l.<br/>
Il trattamento che intendiamo effettuare sulla base di un legittimo interesse della società e del consenso da Lei prestato, ha le seguenti finalità: ricevere e raccogliere le richieste di inserimento professionale, valutare i profili professionali di interesse che emergono dai curricula vitae ricevuti o da altre informazioni da noi acquisite tramite consultazioni di banche di dati o a seguito di ulteriori modalità di fornitura dei dati da parte Sua (es: incontri presso le nostre sedi), gestire tutte le fasi connesse alla ricerca e selezione dei candidati di interesse (comunicazioni con gli interessati, colloqui e interviste valutative, etc). Oltre a tali finalità La informiamo che il trattamento dei Suoi dati personali potrebbe avere altresì la finalità di svolgere elaborazioni di tipo statistico.<br/>
Il trattamento sarà effettuato con le seguenti modalità: i dati saranno trattati in forma cartacea e/o su supporto magnetico, elettronico o telematico (tramite la compilazione di form presenti sul nostro sito web). Laddove il Suo curriculum sia stato ricevuto in formato elettronico o su supporti diversi da quelli cartacei, La informiamo che i relativi files confluiranno in una apposita Banca Dati interna alla nostra azienda.<br/>
I Suoi dati personali potranno essere comunicati a società del Gruppo Birra Peroni s.r.l. di cui è parte la nostra azienda, ad altre società che potrebbero risultare interessate al suo profilo professionale, a soggetti da Lei stesso indicati nel CV ai fini delle verifiche e valutazioni del caso. Ai sensi dell’articolo 13 del Regolamento UE 2016/679, la informiamo inoltre che i Suoi dati personali saranno messi a disposizione del personale amministrativo della nostra azienda incaricato della gestione dei curricula vitae, ciascuno per i propri profili di competenza. I dati comuni potranno essere diffusi attraverso idonei canali di promozione (annunci di settore, riviste specializzate, rubriche cerco/offro lavoro, siti web specialistici, etc).<br/>
La informiamo altresì che i Suoi dati saranno raccolti, trattati e custoditi nel pieno rispetto di quanto previsto dall’art. 32 del Regolamento UE 2016/679, in materia di misure di sicurezza.<br/>
Gli estremi identificativi del Titolare del trattamento sono i seguenti: Birra Peroni s.r.l. – Via Renato Birolli, 8 – CAP 00155. La informiamo altresì che l’elenco aggiornato dei Responsabili del trattamento è da Lei richiedibile presso il dipartimento Risorse Umane di Birra Peroni S.r.l.. o sul sito web www.birraperoni.it. Per eventuali contatti ai fini dell’esercizio dei suoi diritti, potrà utilizzare i medesimi recapiti del titolare del trattamento come sopra riportati.<br/>
I dati saranno conservati presso la sede del Titolare, per i tempi definiti dalla normativa di riferimento. La informiamo altresì che tali dati saranno raccolti, trattati e custoditi nel pieno rispetto di quanto previsto dalle norme di legge.<br/>
E’ in ogni caso possibile per l’interessato avvalersi dei diritti di cui agli articoli del Regolamento UE 2016/679 da 15 a 23 cui espressamente si rinvia, revocando altresì il consenso in qualsiasi momento senza pregiudizio di liceità del trattamento basato sul consenso prestato prima della revoca, nonché proporre reclamo all’Autorità Garante dei dati personali con sede in Piazza di Monte Citorio n.121, 00186 Roma.<br/>
    </p>
)