import React from "react"

export default (
    <p>
        Informacja na temat przetwarzania danych osobowych osób aplikujących na stanowisko pracy w KP, tworzących profil kandydata lub posiadających profil przyszłego pracownika<br/>
1.     Kto jest Administratorem Państwa danych osobowych?<br/>
Zgodnie z art. 13 ust. 1 i ust. 2 ogólnego rozporządzenia o ochronie danych osobowych RODO z dnia 27 kwietnia 2016 r., informujemy, iż administratorem podanych przez Ciebie danych osobowych w utworzonym profilu i/lub dokumentach aplikacyjnych jest Kompania Piwowarska S.A. (dalej KP) z siedzibą w Poznaniu przy ul. Szwajcarskiej 11, 61-285 Poznań. Administrator powołał Inspektora Ochrony Danych, z którym można skontaktować się pod adresem siedziby Administratora lub pod adresem e-mail rodo@asahibeer.pl.<br/>
2.     Jakie dane przetwarzamy w ramach procesu rekrutacyjnego?<br/>
Jeżeli aplikowałeś na konkretne stanowisko pracy w KP, Twoje dane osobowe w zakresie wskazanym w przepisach prawa pracy będą przetwarzane przez KP w celu przeprowadzenia postępowania rekrutacyjnego (art. 6 ust. 1 lit. c RODO), w którym bierzesz udział, natomiast inne dane (np. Twoje zdjęcie, zainteresowania), na podstawie zgody (art. 6 ust. 1 lit. a RODO), która może zostać odwołana w dowolnym czasie.<br/>
Aplikując na dane stanowisko zgadzasz się na przetwarzanie danych osobowych zawartych w Twoim zgłoszeniu rekrutacyjnym (m.in. w formularzu aplikacyjnym), które nie są wymagane przepisami jak np. Twoje zdjęcie, zainteresowania. Jeżeli nie chcesz, abyśmy przetwarzali dodatkowe dane o Tobie, nie umieszczaj ich w swoich dokumentach, na swoim profilu lub w formularzu aplikacyjnym.<br/>
Ponadto KP będzie przetwarzała Twoje dane w celu wzięcia udziału w ankiecie dotyczącej procesu rekrutacji prowadzonej przez KP, jeżeli wyrazisz na to zgodę (art. 6 ust. 1 lit. a RODO), która może zostać odwołana w dowolnym czasie.<br/>
Dodatkowo, jeżeli w dokumentach zawarte są dane, o których mowa w art. 9 ust. 1 RODO (w szczególności np. dane o niepełnosprawności) umieszczając te dane w dokumentach aplikacyjnych lub na profilu kandydata wyrażasz zgodę na ich przetwarzanie przez KP (art. 9 ust. 2 lit. a RODO). Zgoda może zostać odwołana w dowolnym czasie. <br/>
3.     Jakie dane przetwarzamy przy założeniu profilu kandydata?<br/>
 W celu założenia i obsługi profilu kandydata (konta w systemie), przetwarzamy Twoje dane osobowe wskazane przez Ciebie przy tworzeniu profilu. Dane przetwarzamy na podstawie art. 6 ust. 1 lit. b RODO, ponieważ są one niezbędne do realizacji przez nas usługi stworzenia Twojego profilu (założenia konta).<br/>
Jeżeli będziesz chciał otrzymywać powiadomienia o nowych ofertach pracy Twoje dane będziemy przetwarzać na podstawie zgody (art. 6 ust. 1 lit. a RODO).<br/>
 4.     Jakie dane przetwarzamy w procesie przygotowania do zatrudnienia (onboardingu) tj. podczas tworzenia profilu przyszłego pracownika?<br/>
Jeżeli otrzymałaś/eś od nas ofertę zatrudnienia (pracy) będziemy przetwarzać Twoje dane osobowe w celu przygotowania do zakończenia procesu zatrudnienia (art. 6 ust. 1 lit. c RODO).<br/>
Będziemy przetwarzać dane w zakresie imię i nazwisko, adres e-mail, potencjalne stanowisko, miejsce przyszłej pracy oraz numer identyfikacji podatkowej (NIP lub PESEL), płeć, adres zamieszkania, numer telefonu<br/>
Jeżeli Twoje przyszłe stanowisko pracy będzie wymagało od nas zapewnienia Ci środków ochrony indywidulanej (odzieży roboczej), możemy poprosić Cię także o dane dotyczące Twojego rozmiaru odzieży i/lub wymiarów (np..  wzrost, obwód pasa, obwód klatki piersiowej, długość ręki, wewnętrzna długość nogi, długość stopy). Dane te będziemy przetwarzać na podstawie art. 6 ust. 1 lit. c RODO, w celu zapewnienia Ci bezpiecznych i higienicznych warunków pracy.<br/>
 5.     Jak długo przechowujemy Państwa dane?<br/>
 a)     Jeżeli proces rekrutacyjny zakończy się powodzeniem, Twoje dane zostaną włączone do akt osobowych. Jeżeli proces rekrutacyjny nie zakończy się powodzeniem, Twoje dane przechowywane będą jeszcze przez sześć miesięcy od dnia zakończenia procesu rekrutacji w celu realizacji prawnie uzasadnionego interesu KP jakim jest obrona przed ewentualnym roszczeniami w związku z jego przeprowadzeniem.<br/>
Po tym czasie Twoje dane zostaną usunięte.<br/>
 b)     Jeżeli podczas składania aplikacji w systemie wyrazisz na to odrębną zgodę (art. 6 ust. 1 lit. a RODO), KP będzie przetwarzała Twoje dane także w kolejnych naborach pracowników, co oznacza że Twoje dane nie zostaną usunięte w sposób opisany w akapicie powyżej. W przypadku wyrażonej przez Ciebie zgody na wykorzystywane danych osobowych dla celów przyszłych rekrutacji, Twoje dane będą przetwarzane przez okres 5 lat. Twoja zgoda na udział w przyszłych rekrutacjach może zostać odwołana w dowolnym czasie.<br/>
 c)     Jeżeli utworzyłeś profil kandydata, aby śledzić oferty pracy w KP lub otrzymywać powiadomienia o nowych ofertach pracy i ewentualnie w celu zaaplikowania na konkretne stanowisko pracy, Twoje dane przechowywane będą przez okres pięciu lat od dnia stworzenia profilu kandydata.<br/>
Pod koniec 5-letniego okresu otrzymasz od nas powiadomienie, że Twój profil wkrótce wygaśnie. Będziesz mógł wtedy zdecydować czy chcesz przedłużyć jego obowiązywanie. Jeżeli nie wykonasz żadnego działania profil zostanie usunięty z upływem pięciu lat.<br/>
Jednocześnie w każdym czasie może usunąć swój profil i powiązane z nim dane poprzez kliknięcie w prawym górnym rogu przycisku „Opcje”, następnie „Ustawienia”. W prawym dolnym rogu pojawi się przycisk „Usuń profil”, kliknięcie w który powoduje skasowanie profilu z systemu.<br/>
 d)     W przypadku wyrażenia przez Ciebie zgody na wykorzystywane danych osobowych w celu wzięcia udziału w ankiecie dotyczącej procesu rekrutacji prowadzonej przez KP, Twoje dane będą wykorzystywane przez okres 5 lat.<br/>
 e)     Jeżeli otrzymałeś od nas propozycję zatrudnienia i został dla Ciebie utworzony profil przyszłego pracownika (przygotowujący do zatrudnienia) - będziesz miał do niego dostęp maksymalnie na 90 dni przed zatrudnieniem i 40 dni po zawarciu umowy o pracę. Po tym terminie profil zostanie usunięty. Dodatkowo, jeżeli nie dojdzie do podjęcia przez Ciebie zatrudnienia w KP (zawarcia umowy o pracę) Twój profil przyszłego pracownika zostanie usunięty w terminie 30 dni od dnia, w którym poinformujesz nas o rezygnacji z zatrudnienia.<br/>
 6.     Czy przekazujemy Państwa dane podmiotom trzecim?<br/>
Udostępnianie danych podmiotom trzecim, którzy w odosobnionych przypadkach pomagają nam w przeprowadzeniu procesu rekrutacyjnego, odbywa się wyłącznie po ich starannym wyborze i zobowiązaniu ich do ochrony danych osobowych.<br/>
Odbiorcami Twoich danych osobowych mogą być podmioty zaangażowane w realizację procesu rekrutacji, jak również dostawcy systemów i usług IT, księgowych, kancelarie prawne i inne podmioty, z którymi Administrator zawarł umowy o współpracy, a także spółki z grupy Asahi, jeżeli udostępnienie danych jest niezbędne w celu realizacji celów, o których mowa niniejszej klauzuli.<br/>
 Jednocześnie Twoje dane osobowe nie będą przy tym przekazywane do państw trzecich.<br/>
7.     Jakie mają Państwa prawa w związku z przetwarzaniem danych osobowych?<br/>
 Przysługuje Ci prawo żądania dostępu do danych osobowych dotyczących Twojej osoby, ich sprostowania, usunięcia lub ograniczenia przetwarzania oraz prawo do wniesienia sprzeciwu wobec przetwarzania, a także prawo do przenoszenia danych.<br/>
 Ponadto, przysługuje Ci prawo do cofnięcia wyrażonej zgody w dowolnym momencie, które może zostać zrealizować na przykład poprzez przesłanie maila na adres: rodo@asahibeer.pl. Wycofanie zgody nie wpływa na zgodność z prawem przetwarzania, którego dokonano na podstawie wyrażonej przez Ciebie zgody przed jej cofnięciem.<br/>
 Dodatkowo, przysługuje Ci prawo do złożenia skargi do organu nadzorczego – Urzędu Ochrony Danych Osobowych przy ul. Stawki 2, 00-193 Warszawa.<br/>
Podanie przez Ciebie danych osobowych w zakresie wynikającym z art. 22 (1) Kodeksu pracy jest niezbędne, aby uczestniczyć w postępowaniu rekrutacyjnym. Podanie innych danych jest dobrowolne, a za odmowę ich podania nie spotkają Cię jakiekolwiek konsekwencje w prowadzonym procesie rekrutacyjnym.<br/>
 Decyzje dotyczące przeprowadzenia oraz rozstrzygnięcia procesu rekrutacji nie będą podejmowane w sposób zautomatyzowany.<br/>
 8.     Do kogo mogą się Państwo zwrócić w razie pytań dotyczących ochrony danych lub w celu skorzystania z przysługujących Państwo praw?<br/>
 W razie dalszych pytań odnośnie do przetwarzania danych, możesz zwrócić się do Inspektora Ochrony Danych, wykorzystując poniższy adres e-mail:rodo@asahibeer.pl.<br/>
    </p>
)