import React from "react"

export default (
    <p>
        Notă de informare cu privire la prelucrarea datelor personale ale candidaţilor la ocuparea posturilor în cadrul Ursus Breweries S.A.<br/>
1. Cum colectăm şi utilizăm (procesăm) datele dvs. personale .............................. 1<br/>
2. Prezentarea informaţiilor personale ...................................................................... 2<br/>
3. Păstrarea datelor cu caracter personal ................................................................. 4<br/>
4. Drepturile dvs. ........................................................................................................ 4<br/>
5. Transferul de informaţii .......................................................................................... 5<br/>
6. Securitatea .............................................................................................................. 5<br/>
7. Modificare privitoare la Politica de respectare a confidenţialităţii datelor personale .......................................................................................................................... 6<br/>
8. Întrebări suplimentare sau formularea unor reclamaţii ....................................... 6<br/>
Ursus Breweries S.A. (denumit în continuare “Ursus”, “noi” sau un apelativ similar) este o societate pe acţiuni de naţionalitate română, filială a Asahi Breweries Europe Ltd. Noi colectăm şi procesăm mai multe categorii de date personale de la candidaţii noştri şi de la posibilii stagiari (în continuare „dumneavoastră“) ceea ce, în conformitate cu legislaţia Uniunii Europene în domeniul protecţiei datelor, ne califică drept operator al acestor date cu caracter personal.<br/>
Știm că aspectele ce ţin de viaţa dumneavoastră personală sunt deosebit de importante, iar noi tratăm aceste aspecte cu seriozitate. Această Notă de informare descrie politicile şi practicile noastre referitoare la colectarea şi folosirea de către noi a datelor dvs. personale atunci când vă înscrieţi pentru ocuparea unui post în cadrul Ursus, şi descrie şi drepturile pe care le aveţi. Mai exact, veţi găsi mai jos:<br/>
•             • Ce date colectăm despre dumneavoastră;<br/>
•             • Cum folosim şi în general cum prelucrăm aceste date;<br/>
•             • Temeiul pe care ne întemeiem în această prelucrare;<br/>
•             • Cui comunicăm aceste date; şi<br/>
•             • Modalitatea de stocare a datelor.<br/>
Vă rugăm să citiţi cu atenţie această notă de informare pentru a înţelege modul cum prelucrăm datele dumneavoastră personale.<br/>
1. Cum colectăm şi utilizăm (prelucrăm) datele dumneavoastră personale<br/>
1.1 În cadrul Ursus colectăm şi utilizăm oricare dintre următoarele date despre dumneavoastră, iar în cadrul documentului de faţă ne vom referi la acestea drept „date personale“.<br/>
(a) Informaţii din CV/biografie/talent management: informaţiile incluse în candidatură şi în CV / biografie sau informaţii care ne sunt furnizate în alt mod de către dvs. în acest context, cum ar fi numele complet, adresa, adresa de email, nr. de telefon, angajatorii anteriori, calificări profesionale, recomandări, analiza evoluţiei profesionale şi a competenţelor, instruire, schimbări de departament, detalii privind performanţa şi adaptarea la cerinţe.<br/>
Vom utiliza aceste date pentru a lua măsuri (la solicitarea dvs.) înainte de a semna contractul de muncă, cum ar fi să vă contactăm pentru interviuri.<br/>
(b) rezultatele cercetărilor privitoare la identificare şi conformitate, cum ar fi verificări în baze de date privind deţinerile societare şi calitatea de administrator, verificarea posibilei situaţii de faliment personal, verificarea surselor din presă şi reţele de socializare, precum şi verificarea informaţiilor publice privind litigiile.<br/>
Utilizăm datele de mai sus în interesul nostru legitim de a evalua adecvarea candidatului, precum şi confirmarea informaţiilor din CV-uri, biografii şi scrisori de intenţie, precum şi pentru obţinerea unor scrisori de recomandare şi pentru realizarea unor verificări privind performanţele anterioare. Avem de asemenea un interes în asigurarea onoarei şi bunei reputaţii a viitorilor noştri angajaţi, prin urmare considerăm important să verificăm imaginea pe care o are un candidat în presă şi în reţelele de socializare, care este tonul şi direcţia postărilor publice pe reţelele de socializare (de exemplu, nu tolerăm discursurile de incitare la ură, discriminarea şi rasismul), precum şi dacă respectivul candidat este implicat în vreun litigiu care ne poate afecta reputaţia, dacă respectivul candidat este implicat în vreo afacere concurentă, etc. Nu prelucrăm date sensibile (cum ar fi cele referitoare la starea de sănătate) în cadrul acestor verificări, însă putem găsi fără intenţie informaţii privitoare la condamnări penale, în cazul în care aceste informaţii sunt publice (cum sunt cele listate pe portalul instanţelor de judecată).<br/>
 (c) Imaginile aferente sistemului de supraveghere video din sedii, depozite şi fabrici<br/>
Utilizăm aceste date pentru efectuarea unor verificări de securitate, în interesul nostru legitim de a asigura securitatea spaţiilor, a bunurilor şi a persoanelor care se găsesc în spaţiile noastre.<br/>
În cazul în care sunteţi selecţionat(ă) pentru a primi o ofertă, vi se va pune la dispoziţie o notă de informare separată privitoare la prelucrarea datelor cu caracter personal ale angajaţilor noştri. Această notă de informare va acoperi verificările preliminare pe care le efectuăm şi documentele solicitate care ne sunt necesare la încheierea contractului (vizită medicală, act de identitate, în unele cazuri cazierul judiciar, etc.)<br/>
1.2 Sursa datelor personale. Unele dintre datele personale prelucrate sunt furnizate direct de dumneavoastră, iar alte informaţii sunt obţinute indirect de la terţi, cum ar fi agenţii de recrutare şi surse publice (de ex. LinkedIn, Registrul Comerţului, portalul instanţelor).<br/>
2. Cui dezvăluim datele personale<br/>
2.1 Distribuirea datelor în cadrul grupul Asahi<br/>
Datele dumneavoastră personale pot fi distribuite către orice altă societate care este membră a grupului nostru, incluzând şi societatea mamă cu sediul în Japonia, în cazul în care considerăm că acest lucru este în interesul nostru legitim pentru scopuri administrative interne (de ex. stocarea de date, CRM) sau pentru auditarea şi monitorizarea proceselor noastre interne.<br/>
Putem de asemenea să distribuim datele dvs. personale cu societăţi din grupul nostru dacă acestea ne furnizează produse şi servicii, cum ar fi sisteme IT, servicii de resurse umane şi de monitorizare a angajaţilor.<br/>
Accesul la datele dvs. personale este limitat numai acei angajaţi cărora le sunt necesare acele informaţii pentru scopuri profesionale, putând include posibilii dvs. superiori şi alte persoane numite de aceştia pentru îndeplinirea unor sarcini, precum şi angajaţii de la departamentele de resurse umane, servicii corporate, juridic, IT, securitate şi financiar.<br/>
2.2 Dezvăluirea datelor către terți<br/>
Vom partaja partea necesară din datele dvs. personale numai în măsura în care sunt necesare şi numai următoarelor categorii de terţi:<br/>
(a) alte entităţi cum ar fi autorităţi de reglementare, contabili, auditori, avocaţi sau alţi experţi externi, în cazul în care activitatea lor necesită aceste informaţii; şi<br/>
(b) societăţi care ne furnizează produse şi servicii, cum ar fi:<br/>
(i) servicii de resurse umane, cum ar fi verificările de pre-angajare şi activităţile de monitorizare a angajaţilor;<br/>
(ii) agenţii de recrutare;<br/>
(iii) furnizori de sisteme IT şi furnizorii de servicii de asistenţă aferenţi, inclusiv arhivarea de emailuri, furnizorii de servicii de telecomunicații, realizare copii de rezervă şi recuperare în caz de dezastru, servicii de securitate informatică; furnizor de servicii psihometrice şi alţi furnizori de servicii externalizate, cum ar fi stocare în afara spaţiului de producţie propriu şi furnizori de servicii de stocare în sistem cloud.<br/>
De asemenea, vom mai dezvălui datele dvs. personale unor terţi în următoarele situaţii:<br/>
(c) În cazul în care ne solicitaţi sau ne daţi acordul în acest sens;<br/>
(d) Persoanelor care pot demonstra că deţin autoritatea legală de a acţiona în numele dvs.;<br/>
 (e) în cazul în care avem obligaţia de a dezvălui datele dvs. personale pentru a respecta o obligație legală, orice solicitare legală din partea autorităţilor guvernamentale sau executive, şi după cum poate deveni necesar pentru a îndeplini anumite cerinţe de securitate națională sau de aplicare a legii sau a de preveni anumite activităţi ilegale;<br/>
(f) pentru a răspunde oricăror pretenţii, pentru a ne proteja drepturile noastre sau ale unui terţ, pentru a proteja siguranţa oricărei persoane sau pentru a preveni orice activitate ilegală; sau<br/>
(g) pentru a proteja drepturile, proprietăţile sau siguranța Ursus, a angajaţilor săi, a clienţilor săi, a furnizorilor sau a altor persoane.<br/>
Unii din aceşti destinatari (inclusiv afiliaţii noştri) pot utiliza datele dvs. în ţări aflate în afara Zonei Economice Europene. Vă rugăm să consultaţi secţiunea 5 de mai jos pentru mai multe detalii privitoare la acest subiect.<br/>
2.3 Restricţii legate de utilizarea datelor personale de către destinatari<br/>
Terţii cărora le punem la dispoziţie informaţiile dvs. personale în temeiul paragrafelor a), b) şi e) de mai sus sunt limitaţi (prin lege şi prin contract) cu privire la modul în care pot folosi datele dvs. personale pentru scopurile specifice pe care le-am identificat noi. Întotdeauna ne vom asigura că orice terţi cărora le divulgăm voluntar informaţiile dvs. personale sunt supuşi obligațiilor de confidenţialitate şi securitate în acord cu prezenta notă de informare şi legislaţia aplicabilă (pentru evitarea dubiilor, acest lucru nu se poate aplica acolo unde divulgarea nu este decizia noastră, cum sunt situaţiile menţionate la par. c), d), e), f) şi g) de mai sus.).<br/>
Cu excepţia celor detaliate mai sus, noi nu vom divulga, comercializa sau împrumuta vreodată niciuna dintre datele dvs. personale vreunui terţ fără a vă anunţa, sau, dacă este cazul, fără a obţine în prealabil consimțământul dvs.<br/>
3. Reţinerea datelor cu caracter personal<br/>
Datele dvs. personale sunt păstrate doar atât cât este necesar pentru îndeplinirea scopurilor pentru care informaţiile respective sunt prelucrate. La data acestui document, datele personale sunt păstrate pentru următoarele perioade pe care le considerăm necesare în mod rezonabil:<br/>
(a) Sub rezerva alin. b), datele cu caracter personal ale candidaţilor care nu devin angajaţi - timp de şase luni de la sfârşitul etapei de recrutare;<br/>
 (b) Imaginile preluate de la camerele de supraveghere sunt păstrate timp de 30 de zile de la data înregistrării, cu excepţia situaţiei în care este înregistrat un incident, situaţie în care secţiunile de filmare aferente acelor incidente sunt păstrate timp de 3 ani. Facen acest lucru în interesul nostru legitim de a ne permite să constatăm, să exercităm şi să susţinem în instanţă pretenţiile noastre sau ale unui terţ;<br/>
Datele cu caracter personal ale candidaţilor care devin angajaţi sunt păstrate ca parte a datelor angajaţilor, şi supuse politicii noastre referitoare la prelucrarea datelor angajaţilor.<br/>
În situaţia în care vă sunt necesare informaţii suplimentare cu privire la durata de timp pentru care se păstrează informaţiile dvs. personale, vă rugăm să ne contactaţi (consultaţi secțiunea 8 dedesubt).<br/>
4. Drepturile dumneavoastră<br/>
4.1 Aveţi anumite drepturi în ceea ce priveşte datele dvs personale.<br/>
(a) Puteţi solicita accesul la datele cu caracter personale pe care le deţinem în ceea ce vă priveşte. Puteţi de asemenea solicita informaţii despre următoarele: scopul prelucrării; categoriile de date cu caracter personal prelucrate; cine în afară de Ursus ar mai fi putut primi datele de la noi; care a fost sursa informaţiilor (dacă nu ni le-aţi oferit dvs. direct); şi cât de mult vor fi păstrate respectivele date.<br/>
(b) Aveţi dreptul de a corecta (rectifica) datele dvs. care se află în posesia noastră în cazul în care sunt inexacte.<br/>
(c) Puteţi solicita de asemenea ştergerea datelor sau încetarea activităţii de prelucrare a acestora, sub rezerva anumitor excepţii.<br/>
(d) Puteţi de asemenea să solicitaţi încetarea prelucrării datelor dacă acest lucru are loc în temeiul unui interes legitim, sub rezerva anumitor excepţii.<br/>
(e) Aveţi dreptul să ne solicitaţi să transferăm datele pe care le prelucrăm despre dvs. în temeiul consimțământul dvs. sau în îndeplinirea unui contract, către dvs. sau, dacă este fezabil din punct de vedere tehnic, direct către un alt operator.<br/>
(f) În cazul în care nu sunteţi mulţumit(ă) de modul în care vă prelucrăm datele sau de răspunsul primit la o cerere în legătură cu datele dumneavoastră personale, aveţi dreptul de a depune o plângere la autoritatea competentă de protecţie a datelor. Aceasta este fie autoritatea din statul dumneavoastră de domiciliu din cadrul Uniunii Europene (dacă acesta nu este România), fie Autoritatea Naţională pentru Supravegherea Prelucrării Datelor cu Caracter Personal, http://dataprotection.ro/ .<br/>
4.2 În cazul în care doriţi informaţii suplimentare cu privire la drepturile de mai sus sau în cazul în care doriţi să vă exercitaţi oricare dintre aceste drepturi, vă rugăm să ne contactaţi (consultaţi secţiunea 8 de mai jos).<br/>
4.3 Vom avea în vedere toate aceste solicitări şi vă vom oferi un răspuns într-un termen rezonabil (şi în orice timp nu mai mult de o lună, termen pe care îl mai putem prelungi cu încă două luni în cazul în care solicitarea dvs. este complexă). Cu toate acestea, vă rugăm să aveţi în vedere că există excepţii de la unele dintre drepturile menţionate. În cazul în care solicitarea dvs. este refuzată, Ursus vă va oferi o explicaţie cu privire la motivul pentru care solicitarea dvs. a fost respinsă.<br/>
4.4 În cazul în care se aplică vreo excepţie, o să vă semnalăm acest lucru în momentul în care răspundem solicitării dvs. Înainte de a răspunde oricărei solicitări formulate de dvs., vă putem solicita anumite informaţii necesare pentru confirmarea identităţii dvs.<br/>
4.5 În situaţia în care aveţi întrebări în legătură cu modul în care prelucrăm datele dvs. personale, vă rugăm să ne contactaţi (consultaţi secțiunea 8 dedesubt) .<br/>
5. Transferul datelor personale înafara Uniunii Europene<br/>
5.1 Informaţiile personale pot fi prelucrate de personal al nostru care activează în afara Zonei Economice Europene (Uniunea Europeană, Islanda, Norvegia şi Liechtenstein), precum şi de alţi împuterniciţi, membri ai grupului nostru sau terţi, pentru scopurile menţionate la secţiunea 1.1. Puteţi consulta detalii suplimentare cu privire la destinatarii datelor dvs. personale în secţiunea 2 deasupra.<br/>
5.2 În cazul în care furnizăm orice date personale privitoare la dvs. către membri ai grupului nostru sau împuterniciţi dinafara ZEE, vom lua măsuri adecvate pentru a ne asigura că destinatarul protejează informaţiile dvs. personale în mod adecvat, în conformitate cu prevederile prezentei note de informare. Aceste măsuri includ:<br/>
(a) în situaţia furnizorilor de servicii cu sediul în SUA, încheierea clauzelor standard aprobate de Comisia Europeană; sau<br/>
(b) în situaţia furnizorilor de servicii cu sediul în alte ţări aflate în afara Zonei Economice Europene (inclusiv Japonia), vom încheia clauze standard aprobate de Comisia Europeană.<br/>
5.3 Pentru a solicita mai multe detalii cu privire la măsurile luate pentru a va proteja informaţiile personale în cazurile menţionate mai sus ne puteţi contacta la orice moment (vedeţi secţiunea 8 dedesubt).<br/>
6. Securitatea<br/>
6.1 Ursus este determinată să protejeze informaţiile personale împotriva oricărei pierderi, utilizări abuzive, dezvăluiri, modificări, indisponibilizări, acces neautorizat şi distrugere, şi îşi ia toate măsurile rezonabile pentru a asigura confidenţialitatea informaţiilor personale, inclusiv prin utilizarea unor măsuri adecvate de natură organizaţională şi tehnică. Printre măsurile de natură organizaţională, avem în vedere controlul accesului fizic în sediul nostru, instruirea personalului, şi depozitarea dosarelor fizice în fişete încuiate. Măsurile de natură tehnică includ utilizarea criptării, parolarea accesului la sistemele noastre şi utilizarea softurilor antivirus.<br/>
6.2 În procesul de furnizare a datelor cu caracter personal către noi, informaţiile dvs. personale pot fi transferate prin internet. Deşi depunem eforturi susţinute pentru a proteja informaţiile personale pe care ni le puneţi la dispoziţie, schimbul de informaţii dintre noi şi dvs. prin intermediul unei conexiuni la internet nu este 100% sigur. Prin urmare, nu putem garanta securitatea informaţiilor dvs. personale pe care ni le transmiteţi prin internet şi prin urmare transmiterea efectuată în acest fel se face pe riscul dvs. Odată ce am primit informaţiile dvs. personale, vom utiliza proceduri stricte şi metode de securitate pentru a împiedica accesul neautorizat la aceste informaţii.<br/>
7. Modificări privitoare la nota de informare<br/>
Această notă de informare poate fi modificată ori de câte ori considerăm necesar. Orice modificări efectuate la această nota de informare vor fi afişate pe aceeaşi pagină de internet, însă nu vă vor fi aduse la cunoştinţă prin email.<br/>
8. Întrebări suplimentare sau formularea unor reclamaţii<br/>
8.1 În cazul în care aveţi întrebări suplimentare sau dacă doriţi să depuneţi o reclamaţie cu privire la modul în care colectăm, utilizăm sau stocăm informaţiile dvs. personale sau în cazul în care doriţi să vă exercitaţi oricare dintre drepturile pe care le aveţi în legătură cu cu datele dumneavoastră, vă rugăm să ne scrieti la privacy@asahibeer.ro <br/>
De asemenea, puteți contacta Responsabilul cu Protecția Datelor în mod direct, transmițându-i un mesaj email la adresa dataprotection@eu.asahibeer.com <br/>
8.2 Vom cerceta vom încerca să soluţionăm orice astfel de reclamaţie sau cerere cu privire la drepturile dvs. personale.<br/>
8.3 Dacă nu sunteţi mulţumit(ă) de răspunsul primit, puteţi depune o reclamaţie şi la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal. Puteţi găsi informaţii suplimentare privitoare la procedura de mai sus pe pagina http://dataprotection.ro/?page=procedura_de_solutionare_a_plangerilor.<br/>
    </p>
)