import React from "react"

export default (
    <p>
        Odpoveďou na tento inzerát poskytujete prevádzkovateľovi uvedenému v inzeráte na Vami dopytovanú voľnú pracovnú pozíciu svoje osobné údaje za účelom realizácie výberového konania a to na dobu nevyhnutnú pre toto výberové konanie.   <br/>
Spoločnosťou, ktorá vyhlasuje výberové konanie na voľnú pracovnú pozíciu, môže byť:<br/>
a)       Plzeňský Prazdroj, a. s., sídlo: U Prazdroje 64/7, Východní Předměstí, 301 00 Plzeň, IČO: 45357366, spisová značka: B 227 vedená na Krajskom súde v Plzni;<br/>
b)      Asahi CE & Europe Services, s. r. o., sídlo: Ovocný trh 1096/8, Staré Město, 110 00 Praha 1, IČO: 05629152, spisová značka: C 267700 vedená na Mestskom súde v Prahe;<br/>
c)       Plzeňský Prazdroj Slovensko, a. s., sídlo: Pivovarská 9, 082 21 Veľký Šariš, IČO: 31 648 479,  IČ DPH: SK2020522042, právna forma a registrácia: akciová spoločnosť zapísaná v Obchodnom registri OS Prešov v odd.: Sa, vl. č.: 10414/P.<br/>
Odpoveďou na tento inzerát poskytujete prevádzkovateľovi svoje osobné údaje na účely a po dobu realizácie výberového konania. Prevádzkovateľ vykonáva overovanie osobných údajov vo verejne dostupných registroch právnických a fyzických osôb a ďalších verejných zdrojoch, a to hlavne pre účely overenia pravdivosti Vami uvedených skutočností, posúdenia Vašej dôveryhodnosti a kompetencií v rámci výberového konania a z dôvodu predchádzania stretu záujmov medzi Vami a činnosťou a pôsobnosťou prevádzkovateľa. Na strane prevádzkovateľa môžu spracúvanie Vašich osobných údajov zabezpečovať ďalšie spoločnosti poskytujúce technickú podporu, konzultácie alebo administráciu dát.<br/>
V súvislosti so spracovaním Vašich osobných údajov máte právo: (i) na prístup k osobným údajom, (ii) na opravu či doplnenie nepresných alebo nepravdivých osobných údajov, (iii) na vymazanie osobných údajov v prípadoch vymedzených v GDPR, napríklad v prípade, ak osobné údaje už nie sú potrebné na účely, na ktoré boli zhromaždené či inak spracované, alebo ak zistíte, že boli spracovávané protiprávne, (iv) na obmedzenie spracovania osobných údajov v osobitných prípadoch vymedzených v GDPR, (v) na prenosnosť údajov v prípadoch, keď dochádza k spracovaniu na základe súhlasu alebo na základe zmluvy, ktoré sa vykonáva automatizovane, (vi) v prípadoch, keď ku spracovaniu dochádza na základe oprávneného záujmu prevádzkovateľa, vzniesť námietku, po ktorej bude spracovanie vašich osobných údajov ukončené, ak sa nepreukáže, že existujú závažné oprávnené dôvody na spracovanie, ktoré prevažujú nad Vašimi záujmami alebo právami a slobodami, najmä ak je dôvodom prípadné vymáhanie právnych nárokov a (vii) obrátiť sa na Úrad na ochranu osobných údajov.<br/>
Odkazy na informácie pre dotknuté osoby o spracovaní osobných údajov vyššie uvedenými prevádzkovateľmi:<br/>
https://www.prazdroj.cz/ochrana-soukromi,<br/>
https://www.prazdroj.cz/en/privacy-policy,<br/>
https://www.prazdroj.sk/ochrana-sukromia,<br/>
Vo všetkých vyššie uvedených spoločnostiach pôsobí zodpovedná osoba, ktorú môžete kontaktovať (personaldataprotection@eu.asahibeer.com).<br/>
Osobné údaje uvedené v tomto formulári môžu byť sprístupnené spoločnosti LMC, s. r. o., IČO: 264 41 381, so sídlom Praha 7, Jankovcova 1569/2c, PSČ 170 00 ako sprostredkovateľovi.<br/>
Ďalšie informácie o spracovaní údajov spoločnosťou v spoločnosti LMC, s. r. o., poskytuje jej zodpovedná osoba Jan Svoboda, e-mail: dpo@lmc.eu, resp. sú dostupné na https://www.lmc.eu/cs/zasady-ochrany-soukromi/Odpoveďou na tento inzerát poskytujete prevádzkovateľovi uvedenému v inzeráte na Vami dopytovanú voľnú pracovnú pozíciu svoje osobné údaje za účelom realizácie výberového konania a to na dobu nevyhnutnú pre toto výberové konanie.   <br/>
Spoločnosťou, ktorá vyhlasuje výberové konanie na voľnú pracovnú pozíciu, môže byť:<br/>
a)       Plzeňský Prazdroj, a. s., sídlo: U Prazdroje 64/7, Východní Předměstí, 301 00 Plzeň, IČO: 45357366, spisová značka: B 227 vedená na Krajskom súde v Plzni;<br/>
b)      Asahi CE & Europe Services, s. r. o., sídlo: Ovocný trh 1096/8, Staré Město, 110 00 Praha 1, IČO: 05629152, spisová značka: C 267700 vedená na Mestskom súde v Prahe;<br/>
c)       Plzeňský Prazdroj Slovensko, a. s., sídlo: Pivovarská 9, 082 21 Veľký Šariš, IČO: 31 648 479,  IČ DPH: SK2020522042, právna forma a registrácia: akciová spoločnosť zapísaná v Obchodnom registri OS Prešov v odd.: Sa, vl. č.: 10414/P.<br/>
Odpoveďou na tento inzerát poskytujete prevádzkovateľovi svoje osobné údaje na účely a po dobu realizácie výberového konania. Prevádzkovateľ vykonáva overovanie osobných údajov vo verejne dostupných registroch právnických a fyzických osôb a ďalších verejných zdrojoch, a to hlavne pre účely overenia pravdivosti Vami uvedených skutočností, posúdenia Vašej dôveryhodnosti a kompetencií v rámci výberového konania a z dôvodu predchádzania stretu záujmov medzi Vami a činnosťou a pôsobnosťou prevádzkovateľa. Na strane prevádzkovateľa môžu spracúvanie Vašich osobných údajov zabezpečovať ďalšie spoločnosti poskytujúce technickú podporu, konzultácie alebo administráciu dát.<br/>
V súvislosti so spracovaním Vašich osobných údajov máte právo: (i) na prístup k osobným údajom, (ii) na opravu či doplnenie nepresných alebo nepravdivých osobných údajov, (iii) na vymazanie osobných údajov v prípadoch vymedzených v GDPR, napríklad v prípade, ak osobné údaje už nie sú potrebné na účely, na ktoré boli zhromaždené či inak spracované, alebo ak zistíte, že boli spracovávané protiprávne, (iv) na obmedzenie spracovania osobných údajov v osobitných prípadoch vymedzených v GDPR, (v) na prenosnosť údajov v prípadoch, keď dochádza k spracovaniu na základe súhlasu alebo na základe zmluvy, ktoré sa vykonáva automatizovane, (vi) v prípadoch, keď ku spracovaniu dochádza na základe oprávneného záujmu prevádzkovateľa, vzniesť námietku, po ktorej bude spracovanie vašich osobných údajov ukončené, ak sa nepreukáže, že existujú závažné oprávnené dôvody na spracovanie, ktoré prevažujú nad Vašimi záujmami alebo právami a slobodami, najmä ak je dôvodom prípadné vymáhanie právnych nárokov a (vii) obrátiť sa na Úrad na ochranu osobných údajov.<br/>
Odkazy na informácie pre dotknuté osoby o spracovaní osobných údajov vyššie uvedenými prevádzkovateľmi:<br/>
https://www.prazdroj.cz/ochrana-soukromi,<br/>
https://www.prazdroj.cz/en/privacy-policy,<br/>
https://www.prazdroj.sk/ochrana-sukromia,<br/>
Vo všetkých vyššie uvedených spoločnostiach pôsobí zodpovedná osoba, ktorú môžete kontaktovať (personaldataprotection@eu.asahibeer.com).<br/>
Osobné údaje uvedené v tomto formulári môžu byť sprístupnené spoločnosti LMC, s. r. o., IČO: 264 41 381, so sídlom Praha 7, Jankovcova 1569/2c, PSČ 170 00 ako sprostredkovateľovi.<br/>
Ďalšie informácie o spracovaní údajov spoločnosťou v spoločnosti LMC, s. r. o., poskytuje jej zodpovedná osoba Jan Svoboda, e-mail: dpo@lmc.eu, resp. sú dostupné na https://www.lmc.eu/cs/zasady-ochrany-soukromi/<br/>
    </p>
)